# Site settings
title: Dmitry Polyakovsky's software blog
email:
description: > # this means to ignore newlines until "baseurl:"
  My humble software blog.  All feedback is welcomed.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://dmitrypol.github.io" # the base hostname & protocol for your site
twitter_username: dmitrypol
github_username:  dmitrypol

# seo settings
twitter:
  username: dmitrypol
author:
  twitter: dmitrypol

# Build settings
markdown: kramdown
# paginate: 5

defaults:
  -
    values:
      layout: "post"

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  # - jekyll-lunr-js-search
  - jekyll-redirect-from

whitelist:
  - jekyll-seo-tag
  - jekyll-redirect-from

pages_list:
  About: '/about'

include: ['_pages']

theme: minima
